AWSTemplateFormatVersion: 2010-09-09

Transform: 'AWS::Serverless-2016-10-31'

Parameters:

  ParamA:
    Type: String

  ParamB:
    Type: String

Resources:

  Topic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${ParamA}-${ParamB}"

Outputs:

  TopicArn:
    Description: ARN of SNS Topic
    Value: !Ref Topic