AWSTemplateFormatVersion: 2010-09-09

Transform: 'AWS::Serverless-2016-10-31'

Resources:

  Topic:
    Type: AWS::SNS::Topic

Outputs:

  TopicArn:
    Description: ARN of SNS Topic
    Value: !Ref Topic