version: 2.1

orbs:
  cloudformation: davidkelley/hello-user@dev:0.2.3

jobs:

  build:
    docker:
      - image: circleci/node:12.0.0
    steps:
      - checkout
      - run:
          command: npm i
      - run:
          command: npm test
      - run:
          command: cp skeleton.json /tmp/skeleton.json
      - persist_to_workspace:
          root: /tmp
          paths:
            - "*.json"

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  getting-started:
    jobs:
      - build
      - cloudformation/deploy:
          stack-name: davidk-test-stack
          workspace: /tmp/test-workspace
          template-file: template.yml
          input-json: /tmp/test-workspace/parameters.json
          output-json: /tmp/test-workspace/outputs.json
          before-deploy:
            - cloudformation/merge-parameters:
                source-json: keya.json keyb.json
                target-json: /tmp/test-workspace/skeleton.json
                destination-json: /tmp/test-workspace/parameters.json
          requires:
            - build

        