version: 2.1

orbs:
  cloudformation: davidkelley/hello-user@dev:0.0.15

jobs:

  build-and-test:
    docker:
      - image: circleci/node:12.0.0
    steps:
      - checkout
      - run:
          command: npm i
      - run:
          command: npm test
      - run:
          command: cp skeleton.json /tmp/skeleton.json
      - persist_to_workspace:
          root: /tmp
          paths:
            - "*.json"

  print-outputs:
    docker:
      - image: circleci/node:12.0.0
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/test-workspace
      - run:
          command: cat /tmp/test-workspace/outputs.json
      

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  getting-started:
    jobs:
      - build-and-test
      - cloudformation/deploy:
          workspace: /tmp/test-workspace
          stack_name: davidk-test-stack
          template_file: template.yml
          input_json: /tmp/test-workspace/skeleton.json
          output_json: /tmp/test-workspace/outputs.json
          requires:
            - build-and-test
      - print-outputs:
          requires:
            - cloudformation/deploy

        