version: 2.1

orbs:
  cloudformation: davidkelley/hello-user@dev:0.1.1

jobs:

  build-and-test:
    docker:
      - image: circleci/node:12.0.0
    steps:
      - checkout
      - run:
          command: npm i
      - run:
          command: npm test
      - run:
          command: cp skeleton.json /tmp/skeleton.json
      - persist_to_workspace:
          root: /tmp
          paths:
            - "*.json"

  set-parameters:
    executor: cloudformation/cloudformation
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/in
      - run: mkdir /tmp/out
      - cloudformation/merge-parameters:
          source_json: keys.json
          target_json: /tmp/in/skeleton.json
          destination_json: /tmp/out/parameters.json
      - persist_to_workspace:
          root: /tmp/out
          paths:
            - "*.json"

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  getting-started:
    jobs:
      - build-and-test  
      - set-parameters:
          requires:
            - build-and-test
      - cloudformation/deploy:
          stack_name: davidk-test-stack
          workspace: /tmp/test-workspace
          template_file: template.yml
          input_json: /tmp/test-workspace/parameters.json
          output_json: /tmp/test-workspace/outputs.json
          requires:
            - set-parameters

        